# Generated by Django 5.2.7 on 2025-10-28 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThyroidDiagnosis',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identifikator')),
                ('thyroid_image', models.ImageField(help_text='Qalqonsimon bez ultratovush rasmi', upload_to='thyroid_images/%Y/%m/%d/', verbose_name='Ultratovush rasmi')),
                ('age', models.PositiveIntegerField(help_text='Bemorning yoshi', verbose_name='Yosh')),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('country', models.IntegerField(choices=[(0, "O'zbekiston"), (1, "Qozog'iston"), (2, 'Turkmaniston'), (3, 'Tojikiston'), (4, "Qirg'iziston"), (5, 'Boshqa')], default=0, verbose_name='Mamlakat')),
                ('ethnicity', models.IntegerField(choices=[(0, "O'zbek"), (1, 'Rus'), (2, 'Qozoq'), (3, 'Tojik'), (4, 'Turkman'), (5, 'Boshqa')], default=0, verbose_name='Milat')),
                ('family_history', models.BooleanField(default=False, help_text="Oilada qalqonsimon bez kasalligi bo'lganmi?", verbose_name='Oilaviy kasallik tarixi')),
                ('radiation_exposure', models.BooleanField(default=False, help_text="Radiatsiya ta'siriga uchraganmi?", verbose_name="Radiatsiya ta'siri")),
                ('iodine_deficiency', models.BooleanField(default=False, help_text='Yod tanqisligi bormi?', verbose_name='Yod tanqisligi')),
                ('smoking', models.BooleanField(default=False, help_text='Chekadimi?', verbose_name='Chekish')),
                ('obesity', models.BooleanField(default=False, help_text='Semizlik bormi?', verbose_name='Semizlik')),
                ('diabetes', models.BooleanField(default=False, help_text='Qandli diabet bormi?', verbose_name='Qandli diabet')),
                ('tsh_level', models.FloatField(help_text='mIU/L birligida (normal: 0.4-4.0)', verbose_name='TSH darajasi')),
                ('t3_level', models.FloatField(help_text='ng/dL birligida (normal: 80-200)', verbose_name='T3 darajasi')),
                ('t4_level', models.FloatField(help_text='μg/dL birligida (normal: 5.0-12.0)', verbose_name='T4 darajasi')),
                ('nodule_size', models.FloatField(help_text='Santimetrda', verbose_name="Tugun o'lchami")),
                ('notes', models.TextField(blank=True, help_text="Boshqa muhim ma'lumotlar", null=True, verbose_name="Qo'shimcha izohlar")),
                ('diagnosis', models.CharField(blank=True, help_text='AI tomonidan berilgan tashxis', max_length=100, null=True, verbose_name='Tashxis')),
                ('diagnosis_detail', models.TextField(blank=True, help_text="Batafsil tashxis ma'lumoti", null=True, verbose_name='Tashxis tafsiloti')),
                ('confidence', models.FloatField(blank=True, help_text='Foizda (0-100)', null=True, verbose_name='Ishonch darajasi')),
                ('risk_level', models.CharField(blank=True, help_text="Past, O'rta, Yuqori", max_length=50, null=True, verbose_name='Xavf darajasi')),
                ('diagnosis_class', models.CharField(blank=True, choices=[('success', 'Xavfsiz (Benign)'), ('warning', "O'rtacha xavf"), ('danger', 'Yuqori xavf (Malignant)')], max_length=20, null=True, verbose_name='Tashxis klassi')),
                ('prediction_value', models.FloatField(blank=True, help_text='AI model chiqargan qiymat (0-1)', null=True, verbose_name='Model bashorat qiymati')),
                ('recommendations', models.JSONField(blank=True, help_text="Tibbiy tavsiyalar ro'yxati", null=True, verbose_name='Tavsiyalar')),
                ('is_downloaded', models.BooleanField(default=False, help_text='Bemor xulosani yuklab olganmi?', verbose_name='Yuklab olinganmi')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Necha marta yuklab olingan', verbose_name='Yuklab olishlar soni')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi yuklab olish vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Qalqonsimon Bez Tashxisi',
                'verbose_name_plural': 'Qalqonsimon Bez Tashxislari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='main_app_th_created_ef6dcb_idx'), models.Index(fields=['diagnosis_class'], name='main_app_th_diagnos_fdb6a9_idx'), models.Index(fields=['is_downloaded'], name='main_app_th_is_down_ca2cb0_idx')],
            },
        ),
    ]
